/// grad(), jvp() and vjp() -- reverse- and forward-mode automatic
/// differentiation as AST-level source transforms (pre-typecheck), surfaced
/// through the `ad` module. The header below documents grad; jvp's surface,
/// ABI, and subset are documented at `synthesizeJvp` (its subset is a strict
/// superset -- forward mode needs no reverse sweep, so the discipline
/// checks below do not apply to it), vjp's -- the SEEDED reverse mode for an
/// ARRAY-valued function, `f__vjp(args..., __seed, buffers...)` accumulating
/// J^T seed -- at `synthesizeRev`, and the composition driver
/// (`ad.jvp(ad.grad(f))` = HVP) at `expandModule`. jvp accepts array-valued
/// returns too (`(y, J v)`), so the pair is a matrix-free linearization:
/// forward action and adjoint action from one resolved function, no
/// Jacobian formed (plan-fortran-killer-2 section 6.3).
///
/// Surface form: `import ad as ad` then `ad.grad(f)` where `f` is a
/// top-level function in the same module returning a Float scalar. The pass
/// is import-gated (no `import ad` -> no-op; bare `grad(...)` is unbound,
/// same module rule as the ml/ppl surfaces). The expression rewrites to a
/// reference to a synthesized function `f__grad`, so
/// `ad.grad(f)(args..., buffers...)` and `let g = ad.grad(f)` both work:
///
///   function f__grad(p1, ..., pn,                    // originals
///                    __g_pA: mut <type of pA>, ...)   // one out-buffer per
///                                                      // Float-ARRAY param
///       -> Float                                      // the primal value
///       |  (Float, Float, ...)                        // + one gradient per
///                                                      //   Float SCALAR param
///
/// Gradient out-buffers are ACCUMULATED into (callers zero them; repeated
/// calls sum, PyTorch .grad semantics). Int / int-array params (edge lists,
/// sizes) are non-differentiable and get no buffer.
///
/// Why source-to-source, pre-typecheck: the generated derivative is itself
/// type-checked, lowered, and code-generated by the existing pipeline,
/// including the symmetry system, so adjoints of symmetric computations
/// inherit triangular storage with no AD-specific storage logic.
///
/// THE AD-ABLE SUBSET. Differentiated function bodies may contain:
///   - `let x = e` / `let mut x = e` (single-name patterns)
///   - accumulation `x += e`, `x -= e`, `a(i...) += e`, `a(i...) -= e`
///     (and their spelled-out forms `x = x + e` etc.)
///   - general (re)assignment in STRAIGHT-LINE positions; inside loops only
///     the additive-self pattern is allowed on scalars (loop-carried
///     recurrences would need taping/reversal)
///   - element writes `a(i...) = e` (construction of fresh arrays)
///   - `for k in lo..hi { ... }` to any nesting depth (int bounds,
///     non-differentiable); the ADJOINT loop runs in the SAME direction,
///     exact for the accumulation subset
///   - scalar arithmetic + - * / (and `^` by an int literal), unary minus
///   - math intrinsics (exp/log/sqrt/trig/hyperbolic; floor/ceil have zero
///     derivative). lgamma differentiates to digamma, which makes the
///     gamma/beta/poisson log-likelihoods AD-able. NOT digamma itself: its
///     derivative is trigamma, which the language does not have, so it is
///     REFUSED rather than silently differentiated to zero
///     (zeroDerivIntrinsics vs derivRule's None, below)
///   - array reads `a(i...)` at integer index expressions
///   - calls to other AD-able functions in the same module, INLINED
///     (recursion rejected by a depth cap)
///   - float array literals
///
/// Deliberately rejected (clean errors): if/match in differentiated code,
/// combinator computations AND combinator operators, tuple-pattern lets,
/// reads of an accumulator from expressions inside the loop that mutates it,
/// writes to an accumulator after straight-line code has read it,
/// array-alias lets, callees with mut params, unit-carrying and complex
/// parameters/returns (a gradient's units are <loss>/<param>, which this ABI
/// cannot express; complex needs a Wirtinger convention), calls to names
/// with no derivative rule (`abs`, `min`, imports -- silence would drop
/// their term), and user bindings spelled like the synthesized names
/// (`__g_*`, `__t_*`, `__primal` -- shadowing corrupts the sweep).
///
/// Loop-body `let`s are recomputed inside the adjoint loop (recompute-based
/// tape); function-level `let`s stay in scope across the reverse sweep, so
/// nothing else is stored. The C(n+r-1, r) triangular-tape result falls out
/// of storing intermediates in whatever (possibly symmetric) arrays the
/// forward pass already uses.
module Blade.Grad

open Blade.Ast
open Blade.GradCommon
open Blade.GradExpand
open Blade.GradFusion
open Blade.GradPackUnroll
open Blade.GradNormalize
open Blade.GradSweeps

// Re-exported so external modules keep a single Blade.Grad surface
// (Ide.fs reads the tables; TypeCheck.fs wraps the predicates).
let mathIntrinsics = GradCommon.mathIntrinsics
let isMathIntrinsic = GradCommon.isMathIntrinsic
let binaryMathIntrinsics = GradCommon.binaryMathIntrinsics
let isBinaryMathIntrinsic = GradCommon.isBinaryMathIntrinsic
let ternaryMathIntrinsics = GradCommon.ternaryMathIntrinsics
let isTernaryMathIntrinsic = GradCommon.isTernaryMathIntrinsic
let complexMathIntrinsics = GradCommon.complexMathIntrinsics
let isComplexMathIntrinsic = GradCommon.isComplexMathIntrinsic

// Synthesize f__grad

let private gradSuffix = "__grad"
let private vjpSuffix = "__vjp"

/// The unit of a cotangent: <loss unit> / <value unit>, as a surface unit
/// expression, or None when neither carries a unit (the pre-existing bare
/// ABI, byte for byte).
let private cotUnit (lossUnit: UnitExpr option) (valueUnit: UnitExpr option) : UnitExpr option =
    match lossUnit, valueUnit with
    | None, None -> None
    | Some l, None -> Some l
    | None, Some p -> Some (UnitDiv (UnitOne, p))
    | Some l, Some p -> Some (UnitDiv (l, p))

let private floatOfUnit (u: UnitExpr option) : TypeExpr =
    match u with
    | None -> TyNamed ("Float", [])
    | Some ue -> TyNamed ("Float", [TyUnitExpr ue])

/// The declared type of a parameter's cotangent: <loss unit> / <parameter
/// unit> on the parameter's own index domain (plan-fortran-killer-2.md
/// section 6.1). The unit is a surface expression the ordinary checker
/// resolves (scale included), so `Float<km>` against a meter loss declares
/// `meter/km`, and every `+=` into the buffer is held to that signature --
/// the derivative code is unit-checked for free. Conversions INSIDE the body
/// are the one thing the checker must not do silently; `__ad_body` vetoes
/// the additive join and GradNormalize refuses the annotated let.
let rec private cotangentTy (ctx: Ctx) (lossUnit: UnitExpr option) (paramTy: TypeExpr) : TypeExpr =
    match resolveTy ctx paramTy with
    | TyArray (elem, idxs) -> TyArray (cotangentTy ctx lossUnit elem, idxs)
    | t -> floatOfUnit (cotUnit lossUnit (unitArgOf ctx t))

/// Symbolic ELEMENT-unit inference over the normalized body, for the
/// cotangents of intermediate locals. A cotangent accumulator declared bare
/// (`let mut __g_y = 0.0`) adopts any unit at its first `+=` -- but a READ of
/// it is bare, so the next hop `__g_x += __g_y * dy/dx` would carry only
/// `y/x`, and the checker would refuse it against `__g_x`'s declared
/// `loss/x` whenever `y`'s unit differs from the loss's. Declaring
/// `__g_y: Float<loss/y>` closes that gap, which needs `y`'s unit here, before
/// typecheck. The walk mirrors the checker's unit rules on the forms the
/// AD-able subset admits; anything it does not recognize answers Unknown,
/// and that local's cotangent stays bare (a chain through it may then be
/// refused loudly by the checker -- never accepted wrongly).
type private UnitGuess =
    | Known of UnitExpr option
    | Unknown

let private unitGuessOfBody (ctx: Ctx) (fd: FunctionDecl) (stmts: NStmt list) : Map<string, UnitExpr option> =
    let paramUnits =
        fd.Params |> List.choose (fun p -> p.Type |> Option.map (fun t -> p.Name, elemUnitOf ctx t))
        |> Map.ofList
    let mul (a: UnitGuess) (b: UnitGuess) =
        match a, b with
        | Known None, x | x, Known None -> x
        | Known (Some u), Known (Some w) -> Known (Some (UnitMul (u, w)))
        | _ -> Unknown
    let div (a: UnitGuess) (b: UnitGuess) =
        match a, b with
        | x, Known None -> x
        | Known None, Known (Some w) -> Known (Some (UnitDiv (UnitOne, w)))
        | Known (Some u), Known (Some w) -> Known (Some (UnitDiv (u, w)))
        | _ -> Unknown
    /// `+`/`-`: a bare side adopts the other's unit (the checker's join).
    let add (a: UnitGuess) (b: UnitGuess) =
        match a, b with
        | Known None, x | x, Known None -> x
        | Known (Some u), Known (Some _) -> Known (Some u)
        | _ -> Unknown
    let intExponent (e: Expr) =
        match e.Kind with
        | ExprKind.ExprLit (LitInt n) -> Some (int n)
        | ExprKind.ExprLit (LitFloat f) when System.Double.IsFinite f && f = floor f && abs f <= 1024.0 -> Some (int f)
        | _ -> None
    let rec go (env: Map<string, UnitGuess>) (e: Expr) : UnitGuess =
        let g = go env
        match e.Kind with
        | ExprKind.ExprLit _ -> Known None
        | ExprKind.ExprVar n ->
            (match Map.tryFind n env with
             | Some u -> u
             | None -> if Set.contains n ctx.ModuleVals then Unknown else Unknown)
        | ExprKind.ExprTyped (inner, t) ->
            (match elemUnitOf ctx t with
             | Some u -> Known (Some u)
             | None ->
                 // A bare annotation (`: Float`) or a non-Float type keeps the
                 // inner value's unit; an aggregate annotation may still carry
                 // one in its element slot, handled by elemUnitOf above.
                 g inner)
        | ExprKind.ExprBinOp (_, OpMul, a, b) -> mul (g a) (g b)
        | ExprKind.ExprBinOp (_, OpDiv, a, b) -> div (g a) (g b)
        | ExprKind.ExprBinOp (_, (OpAdd | OpSub), a, b) -> add (g a) (g b)
        | ExprKind.ExprBinOp (_, OpMod, a, _) -> g a
        | ExprKind.ExprBinOp (_, OpCaret, a, b) ->
            (match g a, intExponent b with
             | Known None, _ -> Known None
             | Known (Some u), Some n -> Known (Some (UnitPow (u, n)))
             | _ -> Unknown)
        | ExprKind.ExprBinOp (_, (OpEq | OpNeq | OpLt | OpLe | OpGt | OpGe | OpAnd | OpOr), _, _) -> Known None
        | ExprKind.ExprBinOp (_, OpMath2 _, _, _) -> Known None
        | ExprKind.ExprBinOp (_, OpApply, loop, kernel) ->
            // `method_for(A, B) <@> lambda(a, b) -> body` / `method_for(zip(A, B))`
            // / `object_for(k) <@> A`: bind the kernel parameters to the
            // operands' element units and read the body.
            let operandUnits =
                match loop.Kind with
                | ExprKind.ExprMethodFor [ { Kind = ExprKind.ExprZip es } ] -> Some (es |> List.map g)
                | ExprKind.ExprMethodFor es -> Some (es |> List.map g)
                | _ -> None
            (match operandUnits, kernel.Kind with
             | Some us, ExprKind.ExprLambda (ps, _, body) when ps.Length = us.Length ->
                 let env' = List.zip ps us |> List.fold (fun m (p, u) -> Map.add p.Name u m) env
                 go env' body
             | _ -> Unknown)
        | ExprKind.ExprBinOp _ -> Unknown
        | ExprKind.ExprUnaryOp (OpNeg, a) -> g a
        | ExprKind.ExprUnaryOp (OpMath ("abs" | "floor" | "ceil"), a) -> g a
        | ExprKind.ExprUnaryOp (OpMath _, a) ->
            // Transcendental intrinsics take a dimensionless argument and
            // answer one; over a dimensioned argument the checker rules.
            (match g a with Known None -> Known None | _ -> Unknown)
        | ExprKind.ExprUnaryOp ((OpCast _ | OpConj | OpReal | OpImag), a) -> g a
        | ExprKind.ExprUnaryOp ((OpNot | OpArg), _) -> Known None
        | ExprKind.ExprApp (f, args) ->
            // Indexing an array variable (curried spine) reads its element
            // unit; a plain-call intrinsic follows its rule; anything else
            // (a call the inliner left, a lambda-valued name) is unknown.
            let rec spine (h: Expr) = match h.Kind with ExprKind.ExprApp (h', _) -> spine h' | _ -> h
            (match (spine f).Kind with
             | ExprKind.ExprVar n when Map.containsKey n env -> env.[n]
             | ExprKind.ExprVar "abs" -> (match args with [a] -> g a | _ -> Unknown)
             | ExprKind.ExprVar "fma" -> (match args with [a; b; c] -> add (mul (g a) (g b)) (g c) | _ -> Unknown)
             | ExprKind.ExprVar n when isMathIntrinsic n || isBinaryMathIntrinsic n ->
                 if args |> List.forall (fun a -> g a = Known None) then Known None else Unknown
             | _ -> Unknown)
        | ExprKind.ExprArrayLit es ->
            es |> List.fold (fun acc x -> add acc (g x)) (Known None)
        | ExprKind.ExprIf (_, t, f) -> add (g t) (g f)
        | ExprKind.ExprReduce (arr, kernel, init, _) ->
            (match kernel.Kind with
             | ExprKind.ExprSection OpAdd -> add (g arr) (match init with Some i -> g i | None -> Known None)
             | _ -> Unknown)
        | ExprKind.ExprTranspose (a, _, _) | ExprKind.ExprDecompact (a, _) | ExprKind.ExprSort (a, _)
        | ExprKind.ExprGuard (_, a) | ExprKind.ExprPure a | ExprKind.ExprCompute a
        | ExprKind.ExprReplicate (_, a) | ExprKind.ExprUnique a -> g a
        | ExprKind.ExprStack es | ExprKind.ExprSequence es | ExprKind.ExprJoin (es, _) ->
            es |> List.fold (fun acc x -> add acc (g x)) (Known None)
        | ExprKind.ExprGram (a, b) -> mul (g a) (g b)
        | ExprKind.ExprGramApply (a, b, x) -> mul (mul (g a) (g b)) (g x)
        | ExprKind.ExprBlock (stmts, Some fe) ->
            let env' = stmtsEnv env stmts
            go env' fe
        | _ -> Unknown
    and stmtsEnv (env: Map<string, UnitGuess>) (stmts: Stmt list) : Map<string, UnitGuess> =
        stmts |> List.fold (fun m s ->
            match s with
            | StmtLet { Pattern = { Kind = PatternKind.PatVar n }; Value = v } -> Map.add n (go m v) m
            | StmtSpanned (StmtLet { Pattern = { Kind = PatternKind.PatVar n }; Value = v }, _) -> Map.add n (go m v) m
            | _ -> m) env
    let rec nstmtsEnv (env: Map<string, UnitGuess>) (ss: NStmt list) : Map<string, UnitGuess> =
        ss |> List.fold (fun m s ->
            match s with
            | NLet (n, _, v) -> Map.add n (go m v) m
            | NAssign ({ Kind = ExprKind.ExprVar n }, rhs) ->
                // A bare-initialized accumulator adopts the unit of what is
                // accumulated into it (the checker's literal ergonomics).
                (match Map.tryFind n m with
                 | Some (Known None) -> Map.add n (go m rhs) m
                 | _ -> m)
            | NAssign _ -> m
            | NFor (var, _, _, body) -> nstmtsEnv (Map.add var (Known None) m) body |> Map.add var (Known None)) env
    let env0 = paramUnits |> Map.map (fun _ u -> Known u)
    nstmtsEnv env0 stmts
    |> Map.toSeq
    |> Seq.choose (fun (n, u) -> match u with Known u -> Some (n, u) | Unknown -> None)
    |> Map.ofSeq

let private carriesUnit (t: TypeExpr) : bool =
    match t with
    | TyNamed (_, _ :: _) -> true
    | _ -> false

/// The where-clause every synthesized derivative carries: the `__ad_body`
/// conjunct alone (Constraints.adBodyConjunct -- the checker's veto on
/// implicit unit-scale conversion inside the body).
let private adBodyWhere : WhereClause option =
    Some { Commutativity = []; Antisymmetry = []; Parallel = []; Repro = false; TDims = []
           Custom = [ ("__ad_body", []) ] }

/// `synthesize` builds `f__grad` (scalar loss, seed 1.0). With `vjp = true`
/// it builds `f__vjp` for an ARRAY-valued `f` (plan-fortran-killer-2 section
/// 6.3, the reverse half of a matrix-free linearization): the body's value
/// must be a NAMED array (`let y = ..` then `y`, or an array parameter), the
/// synthesized function takes one more parameter after the originals --
/// `__seed`, the cotangent of the output, typed exactly as the return -- and
/// seeds the reverse sweep with it instead of 1.0. Everything else is
/// grad's: cotangent buffers for array params are `mut` out-parameters that
/// ACCUMULATE, scalar-param cotangents come back beside the primal. So
/// `ad.vjp(f)(args..., w, buffers...)` accumulates J^T w, and with
/// `ad.jvp(f)(args..., seeds...)` = (y, J v) the identity
/// `dot(w, J v) = sum over params of dot(J^T w, v)` is checkable exactly.
let private synthesizeRev (ctx: Ctx) (fd: FunctionDecl) (vjp: bool) : Result<FunctionDecl, string> =
    errMode.Value <- (if vjp then "vjp" else "grad")
    let fname = fd.Name
    let modeName = if vjp then "vjp" else "grad"
    let suffix = if vjp then vjpSuffix else gradSuffix
    let seedName = "__seed"
    // The loss's unit, if any: the numerator of every cotangent's unit and
    // the seed's type. For an array-valued output it is the ELEMENT's unit.
    let lossUnit =
        fd.ReturnType |> Option.bind (fun rt ->
            match resolveTy ctx rt with
            | TyArray (elem, _) -> unitArgOf ctx elem
            | _ -> unitArgOf ctx rt)
    let paramTyOf (pname: string) : TypeExpr =
        fd.Params |> List.tryFind (fun q -> q.Name = pname)
        |> Option.bind (fun q -> q.Type)
        |> Option.defaultValue TyFloat64
    // The synthesized name must be free: splicing a second `f__grad` beside a
    // user function of that name would silently shadow one of them.
    (if Map.containsKey (fname + suffix) ctx.Decls then
        err fname $"a function named '{fname}{suffix}' already exists in this module; {modeName} would synthesize a colliding declaration -- rename it"
     else Ok ())
    |> Result.bind (fun () ->
    // Return type must be a Float scalar (checked syntactically; the
    // typechecker re-verifies the generated function anyway). A unit-carrying
    // loss is fine: its unit is the numerator of every cotangent's unit.
    // vjp instead requires an ARRAY of Float.
    let isFloatScalar (t: TypeExpr) =
        isFloatTy t || (match t with TyNamed (("Float" | "Float64" | "Float32"), _ :: _) -> true | _ -> false)
    match vjp, fd.ReturnType |> Option.map (resolveTy ctx) with
    | false, Some t when isFloatScalar t -> Ok ()
    | false, Some _ -> err fname "grad requires a function returning Float (scalar loss); for an array-valued function use ad.vjp"
    | false, None -> err fname "grad requires an explicit `-> Float` return annotation"
    | true, Some (TyArray (elem, _)) when isFloatScalar (resolveTy ctx elem) -> Ok ()
    | true, Some _ -> err fname "vjp requires a function returning an array of Float; for a scalar loss use ad.grad"
    | true, None -> err fname "vjp requires an explicit `-> Array<...>` return annotation"
    |> Result.bind (fun () ->
    // classify parameters, normalize + inline, gate reserved names, validate
    prepareForSweeps ctx fd id ignore false |> Result.bind (fun prep ->
    let stmts = prep.Stmts
    let finalE = prep.FinalE
    (if vjp then
        (match finalE.Kind with
         | ExprKind.ExprVar _ -> Ok ()
         | _ -> err fname "vjp requires the body's value to be a NAMED array (`let y = ...` then `y`, or an array parameter) (v1)")
     else Ok ())
    |> Result.bind (fun () ->
    let scalarDiff =
        prep.Classes |> List.choose (fun (p, c) ->
            match c with DiffScalar -> Some p.Name | _ -> None)
    checkLoopDiscipline fname ctx stmts |> Result.bind (fun () ->
    checkWriteAfterRead fname ctx stmts |> Result.bind (fun () ->
    analyze fname ctx prep.DiffParams prep.ArrayParams stmts finalE |> Result.bind (fun (diff, arrays) ->
    checkNoScalarOverwrite fname diff stmts |> Result.bind (fun () ->
    // full static dims per named array (params, then locals in order) --
    // the C6 reverse rules size cotangent buffers and reindexing loops off
    // this env
    let dimsEnv =
        let paramDims =
            fd.Params |> List.choose (fun p ->
                match p.Type |> Option.map (resolveArrayTy ctx) with
                | Some t -> arrayLiteralExtents t |> Option.map (fun (_, ds) -> (p.Name, ds))
                | None -> None)
            |> Map.ofList
        stmts |> List.fold (fun m st ->
            match st with
            | NLet (n, _, value) ->
                (match staticDimsOf ctx m value with Some ds -> Map.add n ds m | None -> m)
            | _ -> m) paramDims
    let rc = { Fname = fname; Ctx = ctx; Diff = diff; Arrays = arrays; Known = prep.Known
               ArrayIdxTys = prep.ArrayIdxTys; LoopBindings = Map.empty; Dims = dimsEnv
               SortPlans = prep.SortPlans; LuOf = luFactorsOf prep.Stmts; Inlining = [] }

    // cotangent declarations for function-level diff LOCALS (params' array
    // cotangents are mut parameters; scalar-param cotangents are locals).
    // Each is ASCRIBED <loss>/<value> when the symbolic unit walk knows the
    // value's unit (unitGuessOfBody); otherwise it stays bare, exactly as
    // before units were admitted.
    let localUnits = unitGuessOfBody ctx fd stmts
    let ascribeCot (n: string) (zero: Expr) (dims: int list option) : Expr =
        match Map.tryFind n localUnits with
        | Some vu ->
            (match cotUnit lossUnit vu with
             | None -> zero
             | Some cu ->
                 let elemTy = floatOfUnit (Some cu)
                 let ty =
                     match dims with
                     | Some ds -> TyArray (elemTy, ds |> List.map (fun d -> TyIdx (iLit (int64 d))))
                     | None -> elemTy
                 syn (ExprTyped (zero, ty)))
        | None -> zero
    let localDecls =
        stmts |> List.choose (fun s ->
            match s with
            | NLet (n, _, value) when Set.contains n diff ->
                if Set.contains n arrays then
                    let dims = Map.tryFind n dimsEnv
                    match value with
                    | { Kind = ExprKind.ExprArrayLit _ } | ConstFill _ ->
                        zerosLikeLiteral value |> Option.map (fun z -> NLet (dName n, true, ascribeCot n z dims))
                    | _ ->
                        // C6: combinator-built locals get a zero buffer
                        // sized from the dims env (else rejected below)
                        dims |> Option.map (fun ds -> NLet (dName n, true, ascribeCot n (zerosOfDims ds) (Some ds)))
                else Some (NLet (dName n, true, ascribeCot n (fLit 0.0) None))
            | _ -> None)
    // reject function-level diff array locals whose initializer has neither
    // a literal shape nor (C6) a combinator reverse rule with known dims.
    //
    // The REASON is carried alongside the name. One message used to answer
    // for every rejection here, and it said "aliases are not differentiable"
    // -- true of an alias, and actively misleading about the two forms that
    // reach this check most often: `compound` and `<|:>` are neither aliases
    // nor shape-unknown, they are combinators whose reverse rule does not
    // exist, for reasons worth stating.
    let badArrayLocal =
        let dimsMsg (form: string) =
            $"is initialized by {form}, whose shape is not statically known here; the reverse sweep sizes a cotangent BUFFER from it, so a partial answer is not available -- annotate the binding `Array<Float like Idx<n>, ...>`, or build it from operands with literal extents"
        stmts |> List.tryPick (fun s ->
            match s with
            | NLet (n, _, value) when Set.contains n diff && Set.contains n arrays ->
                (match value with
                 | { Kind = ExprKind.ExprArrayLit _ } | ConstFill _ -> None
                 | { Kind = ExprKind.ExprVar _ | ExprKind.ExprTranspose _ | ExprKind.ExprStack _
                          | ExprKind.ExprJoin _ | ExprKind.ExprGram _ | ExprKind.ExprGramApply _ | ExprKind.ExprGuard _
                          | ExprKind.ExprPure _ | ExprKind.ExprCompute _
                          | ExprKind.ExprSort _ | ExprKind.ExprSequence _
                          | ExprKind.ExprReplicate _ } when Map.containsKey n dimsEnv -> None
                 // A sole-halo stencil map the gather route kept (its dims
                 // come from the surface literals; its flow is the gather
                 // arm of GradSweeps.adjointOfInit).
                 | { Kind = ExprKind.ExprBinOp (_, OpApply, _, _) } when Map.containsKey n dimsEnv -> None
                 // A solve against LU factors: shaped like its right-hand side,
                 // flowed by GradSweeps.adjointOfInit's lu arm.
                 | { Kind = ExprKind.ExprApp ({ Kind = ExprKind.ExprVar op }, _) } when isLuSolveName op && Map.containsKey n dimsEnv -> None
                 // The `pure`/`compute`/annotation wrappers are transparent
                 // to WHICH combinator this is, so the specific arms below
                 // look through them: `a <|:> b |> compute` parses with the
                 // `compute` outermost and would otherwise be reported as a
                 // shape problem rather than as the fallback it is.
                 | _ ->
                 let rec peel (e: Expr) =
                     match e.Kind with
                     | ExprKind.ExprCompute i | ExprKind.ExprPure i | ExprKind.ExprTyped (i, _) -> peel i
                     | _ -> e
                 match (peel value).Kind with
                 | ExprKind.ExprCompound _ ->
                     Some (n, "is initialized by `compound`, a GATHER through a mask. Its adjoint is the scatter `cot <|:> zeros` -- spellable in the surface (plan-ad-combinators.md 2.12) but a whole-array statement the reverse lane has no rule for, and the compacted extent is a RUNTIME value the static shape env cannot hold (v1). Forward mode (`ad.jvp`) differentiates it; in reverse, apply the mask outside the differentiated function")
                 | ExprKind.ExprBinOp (_, OpFallback, _, _) ->
                     Some (n, "is initialized by `<|:>`, which selects by ALLOCATION rather than by value -- linear in both legs, and forward mode differentiates it for exactly that reason. Its adjoint is a storage-keyed SPLIT, and which split (dense-left copies the cotangent whole; compound-left routes it through the mask and its complement) depends on the left operand's INDEX TYPE -- which this pre-typecheck transform cannot see (v1). Use `ad.jvp`, or move the fallback outside the differentiated function")
                 | _ ->
                 match value with
                 | { Kind = ExprKind.ExprVar _ } -> Some (n, dimsMsg "an array alias")
                 | { Kind = ExprKind.ExprTranspose _ | ExprKind.ExprStack _
                          | ExprKind.ExprJoin _ | ExprKind.ExprGram _ | ExprKind.ExprGramApply _ | ExprKind.ExprGuard _
                          | ExprKind.ExprPure _ | ExprKind.ExprCompute _
                          | ExprKind.ExprSort _ | ExprKind.ExprSequence _
                          | ExprKind.ExprReplicate _ } -> Some (n, dimsMsg "a reindexing combinator")
                 | _ ->
                     Some (n, "must be initialized by an array literal, a constant fill, or a combinator with a reverse rule (`transpose`/`stack`/`sequence`/`replicate`/`join`/`gram`/`guard`/`sort`/`pure`/`compute`); a bare alias or an unsupported combinator is not differentiable in reverse mode"))
            | _ -> None)
    match badArrayLocal with
    | Some (n, why) -> err fname $"differentiable array local '{n}' {why}"
    | None ->
    // Scalar-parameter cotangents are locals, declared with their unit when
    // there is one (a bare `0.0` adopts any unit at its first `+=`, but the
    // RETURNED value must carry <loss>/<param> for the caller's checks).
    let scalarCots =
        scalarDiff |> List.map (fun p ->
            let cty = cotangentTy ctx lossUnit (paramTyOf p)
            let zero = if carriesUnit cty then syn (ExprTyped (fLit 0.0, cty)) else fLit 0.0
            NLet (dName p, true, zero))

    // seed: adjoint of the final expression with cotangent 1.0. The seed is
    // d(loss)/d(loss) -- DIMENSIONLESS, whatever the loss measures; every
    // cotangent below it acquires <loss>/<value> through the partials. vjp
    // seeds with the caller's cotangent of the output instead.
    (if vjp then
        // The seed is an ARRAY: accumulate it cell by cell onto the output's
        // cotangent buffer (a whole-array `+=` inside a function body is not
        // an emitter shape; the indexed loop is exactly what every other
        // array cotangent flow emits).
        match finalE.Kind with
        | ExprKind.ExprVar y when Set.contains y diff ->
            (match Map.tryFind y dimsEnv with
             | Some dims ->
                 Ok (accumLoop ctx dims
                        (fun idx -> syn (ExprApp (v (dName y), idx)))
                        (fun idx -> syn (ExprApp (v seedName, idx))))
             | None -> err fname "vjp: the returned array needs statically-known dims to seed its cotangent (v1)")
        | _ -> Ok []   // an inactive output: nothing depends on the parameters
     else adjointOf rc finalE (fLit 1.0))
    |> Result.bind (fun seed ->
    // reverse sweep over the statements
    let folded =
        List.rev stmts
        |> traverseR (adjointOfStmt rc)
        |> Result.map List.concat
    folded |> Result.map (fun reverse ->

    // assemble: forward + primal + cot decls + seed + reverse + return
    let primalName = "__primal"
    let fwd = toStmts stmts @ [ StmtLet { Pattern = synPat (PatVar primalName)
                                          Type = None
                                          Value = finalE
                                          Mutability = BindLet } ]
    let cotDecls = toStmts (localDecls @ scalarCots)
    let revStmts = toStmts (seed @ reverse)
    let retExpr =
        match scalarDiff with
        | [] -> v primalName
        | ss -> syn (ExprTuple (v primalName :: (ss |> List.map (fun p -> v (dName p)))))
    let retTy =
        match scalarDiff with
        | [] -> fd.ReturnType
        | ss -> Some (TyTuple ((Option.defaultValue TyFloat64 fd.ReturnType)
                               :: (ss |> List.map (fun p -> cotangentTy ctx lossUnit (paramTyOf p)))))
    let seedParams =
        if vjp then [ { Name = seedName; Type = fd.ReturnType; Mutability = Immutable; Default = None; NameSpan = noSpan } ]
        else []
    let gradParams =
        fd.Params
        @ seedParams
        @ (prep.Classes |> List.choose (fun (p, c) ->
             match c with
             | DiffArray ->
                 Some { Name = dName p.Name
                        Type = p.Type |> Option.map (cotangentTy ctx lossUnit)
                        Mutability = Mutable; Default = None; NameSpan = noSpan }
             | _ -> None))
    { Name = fname + suffix
      TypeParams = fd.TypeParams
      Params = gradParams
      WhereClause = adBodyWhere
      ReturnType = retTy
      Body = inheritSpan fd.Body (ExprBlock (fwd @ cotDecls @ revStmts, Some retExpr))
      IsStatic = false
      NameSpan = noSpan }))))))))))

let private synthesize (ctx: Ctx) (fd: FunctionDecl) : Result<FunctionDecl, string> =
    synthesizeRev ctx fd false

let private synthesizeVjp (ctx: Ctx) (fd: FunctionDecl) : Result<FunctionDecl, string> =
    synthesizeRev ctx fd true

// Synthesize f__jvp -- forward mode at grad parity (v1)
//
// Same admissible subset, enforced by running the SAME discipline checks,
// so the jvp-vs-grad differential gate covers every accepted program (F2
// widens by deleting check calls, not rewriting the transform). The ABI
// differs where the mode does: tangent INPUTS -- one per differentiable
// param, appended in original param order, each typed with the primal
// param's annotation VERBATIM (tangents live in the same space, units
// included; bare Float is unit-polymorphic so substitution would defeat
// unit checking) -- and a `(primal, tangent)` tuple return. No mut
// buffers: forward mode does not accumulate, and `wrt` selection is just
// a zero seed.

let private jvpSuffix = "__jvp"

let private synthesizeJvp (ctx: Ctx) (trusted: bool) (fd: FunctionDecl) : Result<FunctionDecl, string> =
    errMode.Value <- "jvp"
    let fname = fd.Name
    let isFloatish (t: TypeExpr) =
        isFloatTy t || (match t with TyNamed (("Float" | "Float64" | "Float32"), _ :: _) -> true | _ -> false)
    (if Map.containsKey (fname + jvpSuffix) ctx.Decls then
        err fname $"a function named '{fname}{jvpSuffix}' already exists in this module; jvp would synthesize a colliding declaration -- rename it"
     else Ok ())
    |> Result.bind (fun () ->
    match fd.ReturnType |> Option.map (resolveTy ctx) with
    | Some t when isFloatish t -> Ok ()   // units included: the tangent carries the same
    // All-Float tuples: the shape of a synthesized source's return
    // (f__grad's `(primal, dscalars...)`), differentiated for the
    // composition routes. The jvp return interleaves flat:
    // components, then their tangents.
    | Some (TyTuple ts) when ts |> List.forall (fun t -> isFloatish (resolveTy ctx t)) -> Ok ()
    // ARRAY-VALUED returns (plan-fortran-killer-2 section 6.3): the tangent
    // of an array local IS an array expression already (every array let
    // carries its `__t_` twin through the sweep), so a body whose value is
    // an array (or a tuple mixing arrays and scalars) returns `(y, dy)` the
    // same way -- components then tangents, flat. The array-output JVP is
    // the forward half of a matrix-free linearization; `ad.vjp` is the
    // reverse half.
    | Some (TyArray (elem, _)) when isFloatish (resolveTy ctx elem) -> Ok ()
    | Some (TyTuple ts) when ts |> List.forall (fun t ->
                                    match resolveTy ctx t with
                                    | TyArray (elem, _) -> isFloatish (resolveTy ctx elem)
                                    | rt -> isFloatish rt) -> Ok ()
    | Some _ -> err fname "jvp requires a function returning Float, an array of Float, or a tuple of those (v1)"
    | None -> err fname "jvp requires an explicit `-> Float` (or `-> Array<...>`) return annotation"
    |> Result.bind (fun () ->
    // Tuple-returning sources (f__grad's `(primal, dscalars...)`) sweep
    // per component; the surrogate keeps taint/validation walks off the
    // tuple node itself.
    let surrogateOf (finalE: Expr) =
        (match finalE.Kind with
         | ExprKind.ExprTuple es -> es
         | _ -> [finalE])
        |> List.reduce add
    // Pick the first depth-indexed tangent prefix no existing name uses
    // (composition rounds each get their own; see tangentPrefix).
    let pickTangentPrefix (allNames: string list) =
        tangentPrefix.Value <-
            (let rec pick k =
                let cand = if k = 0 then "__t_" else $"__t{k}_"
                if allNames |> List.exists (fun n -> n.StartsWith cand) then pick (k + 1) else cand
             pick 0)
    prepareForSweeps ctx fd surrogateOf pickTangentPrefix trusted |> Result.bind (fun prep ->
    let stmts = prep.Stmts
    let finalComps =
        match prep.FinalE.Kind with
        | ExprKind.ExprTuple es -> es
        | _ -> [prep.FinalE]
    // F2: grad's three discipline checks (write-after-read, scalar
    // overwrite, loop discipline) exist ONLY to keep the reverse sweep's
    // final-value re-evaluation sound (their own doc comments say so).
    // Forward tangents flow in program order beside the primal -- every
    // tangent assignment is emitted before its primal and reads
    // pre-assignment values -- so overwrites, loop-carried recurrences,
    // and accumulator reads all differentiate exactly and none of the
    // checks run here.
    analyze fname ctx prep.DiffParams prep.ArrayParams stmts prep.SweepFinal |> Result.bind (fun (diff, arrays) ->
    // No array-local literal restriction here (C1): grad needs one because
    // it must synthesize a ZERO COTANGENT BUFFER of the right shape and can
    // only read a shape off a literal -- and an alias makes cotangent
    // identity untrackable. Forward mode builds no buffers: the tangent of
    // a local IS the tangent expression of its initializer, so aliases and
    // linear combinators differentiate directly, and an initializer with no
    // tangent rule is refused by the sweep itself.
    // Let-bound loop objects are resolved at their APPLICATION sites, so their
    // environment starts EMPTY and grows as the sweep passes each `let`
    // (`noteLoopBinding`). It used to be collected up front over the whole
    // body, first-wins, which answered a re-`let` of the same name with the
    // FIRST loop -- the second computation's tangent then iterated the first
    // one's operands.
    let rc = { Fname = fname; Ctx = ctx; Diff = diff; Arrays = arrays; Known = prep.Known
               ArrayIdxTys = prep.ArrayIdxTys; LoopBindings = Map.empty
               Dims = Map.empty; SortPlans = prep.SortPlans; LuOf = luFactorsOf prep.Stmts; Inlining = [] }

    // tangent-interleaved body + (primal, tangent) return
    let sweptR = tangentOfStmts rc stmts
    sweptR |> Result.bind (fun (rcEnd, swept) ->
    finalComps
    |> traverseR (tangentOfExpr rcEnd)
    |> Result.map (fun tangentComps ->
    // Return: components then their tangents, flat -- `(p, t)` for the
    // scalar case, `(p, ds..., tp, tds...)` for a tuple-returning source.
    // Direct tuple of pure expressions; no intermediate lets (a trusted
    // source already binds `__primal`, so a fresh let would shadow it).
    let retExpr = syn (ExprTuple (finalComps @ tangentComps))
    let retTys =
        match fd.ReturnType |> Option.map (resolveTy ctx) with
        | Some (TyTuple ts) -> ts @ ts
        | rt -> let s = Option.defaultValue TyFloat64 rt in [s; s]
    let jvpParams =
        fd.Params
        @ (prep.Classes |> List.choose (fun (p, c) ->
             match c with
             | DiffArray | DiffScalar ->
                 Some { Name = tName p.Name; Type = p.Type; Mutability = p.Mutability; Default = None; NameSpan = noSpan }
             | NonDiff -> None))
    { Name = fname + jvpSuffix
      TypeParams = fd.TypeParams
      Params = jvpParams
      WhereClause = adBodyWhere
      ReturnType = Some (TyTuple retTys)
      Body = inheritSpan fd.Body (ExprBlock (toStmts swept, Some retExpr))
      IsStatic = false
      NameSpan = noSpan }))))))

// Call-site rewriting + program expansion

/// Rewrite alias.grad(f) / alias.jvp(f) call sites in an expression.
/// Requests are recorded in DISCOVERY order (post-order, so an inner
/// ad.grad(f) precedes the outer ad.jvp(...) that consumes its result),
/// and `anticipated` carries the names the pass itself will synthesize --
/// which is what makes composition (`ad.jvp(ad.grad(f))`, the HVP route;
/// `ad.jvp(ad.jvp(f))`, second-order forward) legal arguments.
let rec private rewriteExpr (requestsOrdered: ResizeArray<string * string>)
                            (anticipated: System.Collections.Generic.HashSet<string>)
                            (declNames: Set<string>) (aliases: Set<string>) (e: Expr) : Result<Expr, string> =
    let r = rewriteExpr requestsOrdered anticipated declNames aliases
    let rList es = traverseR r es
    let re k = inheritSpan e k
    match e.Kind with
    // Qualified: `alias.grad(f)` / `alias.jvp(f)` with alias bound by
    // `import ad`. Bare `grad(...)` is not recognized -- the AD surface is
    // a module, not a language-wide name (same rule as the ml/ppl surfaces).
    | ExprKind.ExprApp ({ Kind = ExprKind.ExprField ({ Kind = ExprKind.ExprVar alias }, (("grad" | "jvp" | "vjp") as which)) }, args) when Set.contains alias aliases ->
        (match args with
         | [arg0] ->
             // Rewrite the argument FIRST so composition works: the inner
             // form becomes a bare synthesized-name reference before this
             // arm inspects it.
             r arg0 |> Result.bind (fun arg0' ->
                 match arg0'.Kind with
                 | ExprKind.ExprVar fname when Set.contains fname declNames || anticipated.Contains fname ->
                     let suffix = if which = "grad" then gradSuffix elif which = "vjp" then vjpSuffix else jvpSuffix
                     requestsOrdered.Add (which, fname)
                     anticipated.Add (fname + suffix) |> ignore
                     Ok (re (ExprVar (fname + suffix)))
                 | ExprKind.ExprVar fname ->
                     Error $"{which}: '{fname}' is not a top-level function in this module ({which} differentiates same-module named functions)"
                 | _ -> Error $"{which}: argument must be a named top-level function (e.g. ad.{which}(loss))")
         | _ -> Error $"{which}: expects exactly one argument, the function to differentiate")
    | ExprKind.ExprLit _ | ExprKind.ExprVar _ -> Ok e
    | ExprKind.ExprApp (f, args) ->
        r f |> Result.bind (fun f' -> rList args |> Result.map (fun args' -> re (ExprApp (f', args'))))
    | ExprKind.ExprBinOp (m, op, l, rr) ->
        r l |> Result.bind (fun l' -> r rr |> Result.map (fun r' -> re (ExprBinOp (m, op, l', r'))))
    | ExprKind.ExprUnaryOp (op, inner) -> r inner |> Result.map (fun i -> re (ExprUnaryOp (op, i)))
    | ExprKind.ExprTyped (inner, t) -> r inner |> Result.map (fun i -> re (ExprTyped (i, t)))
    | ExprKind.ExprAssign (l, rr) ->
        r l |> Result.bind (fun l' -> r rr |> Result.map (fun r' -> re (ExprAssign (l', r'))))
    | ExprKind.ExprTuple es -> rList es |> Result.map (fun es' -> re (ExprTuple es'))
    | ExprKind.ExprArrayLit es -> rList es |> Result.map (fun es' -> re (ExprArrayLit es'))
    | ExprKind.ExprDotDot (l, h) ->
        r l |> Result.bind (fun l' -> r h |> Result.map (fun h' -> re (ExprDotDot (l', h'))))
    | ExprKind.ExprIf (c, t, f) ->
        r c |> Result.bind (fun c' ->
        r t |> Result.bind (fun t' ->
        r f |> Result.map (fun f' -> re (ExprIf (c', t', f')))))
    | ExprKind.ExprLet (binding, body) ->
        r binding.Value |> Result.bind (fun v' ->
        r body |> Result.map (fun b' -> re (ExprLet ({ binding with Value = v' }, b'))))
    | ExprKind.ExprBlock (stmts, finalE) ->
        let rec rStmt (s: Stmt) : Result<Stmt, string> =
            match s with
            | StmtSpanned (inner, sp) -> rStmt inner |> Result.map (fun i -> StmtSpanned (i, sp))
            | StmtLet binding -> r binding.Value |> Result.map (fun v' -> StmtLet { binding with Value = v' })
            | StmtExpr e2 -> r e2 |> Result.map StmtExpr
            | StmtAssign (l, op, rr) ->
                r l |> Result.bind (fun l' -> r rr |> Result.map (fun r' -> StmtAssign (l', op, r')))
            | StmtForIn (var, range, body) ->
                r range |> Result.bind (fun range' ->
                    body |> traverseR rStmt
                    |> Result.map (fun body' -> StmtForIn (var, range', body')))
        stmts |> traverseR rStmt
        |> Result.bind (fun stmts' ->
            match finalE with
            | Some fe -> r fe |> Result.map (fun fe' -> re (ExprBlock (stmts', Some fe')))
            | None -> Ok (re (ExprBlock (stmts', None))))
    | ExprKind.ExprLambda (ps, w, body) -> r body |> Result.map (fun b -> re (ExprLambda (ps, w, b)))
    | ExprKind.ExprMatch (scrut, cases) ->
        r scrut |> Result.bind (fun s' ->
            cases |> traverseR (fun c -> r c.Body |> Result.map (fun b -> { c with Body = b }))
            |> Result.map (fun cs' -> re (ExprMatch (s', cs'))))
    | _ -> Ok e   // exotic containers: grad not expected inside

/// `import ad [as _]` -- the module this transform is surfaced through.
let private isAdImport (d: Located<Decl>) =
    match d.Value with
    | DeclImport (["ad"], _) -> true
    | _ -> false

/// Aliases bound to `ad` in this decl list. Errors on a selective
/// `from ad import ...` (it would reintroduce a global name).
let private adAliasesOf (decls: Located<Decl> list) : Result<Set<string>, string> =
    decls |> List.fold (fun acc d ->
        acc |> Result.bind (fun set ->
            match d.Value with
            | DeclImport (["ad"], ImportQualified aliasOpt) ->
                Ok (Set.add (aliasOpt |> Option.defaultValue "ad") set)
            | DeclImport (["ad"], ImportSelective _) ->
                Error "`ad` supports only `import ad [as <alias>]`; a selective `from ad import ...` would reintroduce global names"
            | _ -> Ok set))
        (Ok Set.empty)

/// Expand alias.grad() over one module's declarations. Import-gated: with no
/// `import ad`, the pass is a no-op and bare `grad(...)` is simply unbound.
let private expandModule (decls: Located<Decl> list) : Result<Located<Decl> list, string> =
    adAliasesOf decls |> Result.bind (fun aliases ->
    if Set.isEmpty aliases then Ok decls
    else
    let decls = decls |> List.filter (not << isAdImport)
    let funcDecls =
        decls |> List.choose (fun d ->
            match d.Value with
            | DeclFunction fd -> Some (fd.Name, fd)
            | _ -> None)
        |> Map.ofList
    // Transparent same-module type aliases, so parameter classification can
    // see through `type Speed = Float<mps>`.
    let typeAliases =
        decls |> List.collect (fun d ->
            match d.Value with
            | DeclType (TyDeclAlias (n, [], body)) -> [(n, body)]
            | DeclType (TyDeclMutualGroup (members, _)) -> members
            | _ -> [])
        |> Map.ofList
    // Module-level value binding names: constant data for the adjoint's
    // known-name check (tuple patterns contribute each bound name).
    let rec patNames (p: Pattern) : string list =
        match p.Kind with
        | PatternKind.PatVar n -> [n]
        | PatternKind.PatTuple ps -> ps |> List.collect patNames
        | _ -> []
    let moduleVals =
        decls |> List.collect (fun d ->
            match d.Value with
            | DeclLet b | DeclStatic b -> patNames b.Pattern
            | _ -> [])
        |> Set.ofList
    // What each FUNCTION declaration can see: everything declared above it,
    // plus itself (a named function may self-recurse; mutual recursion is
    // BL2001). Snapshotted in declaration order rather than collected
    // whole-module, because pipeline fusion resolves stage kernels through
    // these -- and a whole-module map would let a body fuse a function or a
    // `let` declared BELOW it, turning a program the checker rejects into one
    // that compiles and runs.
    //
    // ONE fold, over `ModuleLet` records: the value and the annotation are
    // two projections of the same single-name binding, and a rebind has to
    // move both together. Non-PatVar (destructuring) bindings still REBIND
    // their names -- nothing here can say what a component holds, so they are
    // dropped rather than left pointing at an earlier binding of the name.
    let prefixVisible, moduleLets =
        decls
        |> List.fold (fun (fns, lets, snaps) d ->
            match d.Value with
            | DeclFunction fd ->
                let fns' = Map.add fd.Name fd fns
                (fns', lets, Map.add fd.Name (fns', lets) snaps)
            | DeclLet ({ Pattern = { Kind = PatternKind.PatVar nm } } as b)
            | DeclStatic ({ Pattern = { Kind = PatternKind.PatVar nm } } as b) ->
                (fns, Map.add nm { Value = b.Value; Ty = b.Type } lets, snaps)
            | DeclLet b | DeclStatic b ->
                let names = patternBoundNames b.Pattern
                (fns,
                 names |> List.fold (fun (m: Map<string, ModuleLet>) n -> Map.remove n m) lets,
                 snaps)
            | _ -> (fns, lets, snaps))
            (Map.empty, Map.empty, Map.empty)
        |> (fun (_, lets, snaps) -> (snaps, lets))
    // Source span per differentiable function, for stamping synthSpan so
    // syn-based derivative builders carry the differentiated decl's location.
    let funcSpans =
        decls |> List.choose (fun d ->
            match d.Value with
            | DeclFunction fd -> Some (fd.Name, d.Span)
            | _ -> None)
        |> Map.ofList
    let declNames = funcDecls |> Map.toSeq |> Seq.map fst |> Set.ofSeq
    let requestsOrdered = ResizeArray<string * string>()
    let anticipated = System.Collections.Generic.HashSet<string>()
    // rewrite call sites everywhere
    let rewritten =
        decls |> traverseR (fun d ->
            let mapped =
                match d.Value with
                | DeclFunction fd ->
                    rewriteExpr requestsOrdered anticipated declNames aliases fd.Body
                    |> Result.map (fun b -> DeclFunction { fd with Body = b })
                | DeclLet binding ->
                    rewriteExpr requestsOrdered anticipated declNames aliases binding.Value
                    |> Result.map (fun v' -> DeclLet { binding with Value = v' })
                | DeclStatic binding ->
                    rewriteExpr requestsOrdered anticipated declNames aliases binding.Value
                    |> Result.map (fun v' -> DeclStatic { binding with Value = v' })
                | other -> Ok other
            mapped |> Result.map (fun value -> { d with Value = value }))
    rewritten |> Result.bind (fun decls' ->
        if requestsOrdered.Count = 0 then Ok decls'
        else
            let ctx = { Decls = funcDecls; TypeAliases = typeAliases; ModuleVals = moduleVals
                        ModuleLets = moduleLets; Fresh = ref 0
                        NormMemo = System.Collections.Generic.Dictionary()
                        PackMemo = System.Collections.Generic.Dictionary() }
            // Synthesize in DISCOVERY order against a GROWING decl map:
            // inner requests precede the outer requests that consume them,
            // so by the time `ad.jvp(ad.grad(f))` synthesizes the outer
            // half, f__grad is an ordinary available declaration.
            let mutable available = funcDecls
            let madeOrder = ResizeArray<string>()
            let madeMap = System.Collections.Generic.Dictionary<string, FunctionDecl * string>()
            /// The context a body may resolve through: the prefix snapshot at
            /// its own declaration, widened with the SYNTHESIZED declarations
            /// (which are spliced beside their root, so they are always in
            /// scope for each other). A synthesized source inherits its root's
            /// snapshot -- it was built from a body that already passed here.
            let ctxFor (fname: string) =
                let rec snapshot n =
                    match Map.tryFind n prefixVisible with
                    | Some s -> s
                    | None ->
                        match madeMap.TryGetValue n with
                        | true, (_, src) -> snapshot src
                        | _ -> (funcDecls, moduleLets)
                let (fns, lets) = snapshot fname
                let withSynth =
                    available |> Map.fold (fun acc n fd ->
                        if Map.containsKey n funcDecls then acc else Map.add n fd acc) fns
                // A FRESH normalization memo per request: `withSynth` differs
                // between requests, and a fragment normalized against one
                // prefix snapshot must not answer for another.
                { ctx with Decls = withSynth; ModuleLets = lets
                           NormMemo = System.Collections.Generic.Dictionary()
                           PackMemo = System.Collections.Generic.Dictionary() }
            let synthResult =
                requestsOrdered
                |> Seq.distinct
                |> Seq.fold (fun acc (mode, fname) ->
                    acc |> Result.bind (fun () ->
                        let suffix = if mode = "grad" then gradSuffix elif mode = "vjp" then vjpSuffix else jvpSuffix
                        let synthName = fname + suffix
                        if madeMap.ContainsKey synthName then Ok ()
                        else
                        match Map.tryFind fname available with
                        | None ->
                            Error $"{mode}: '{fname}' is not available to differentiate (compose ad.grad/ad.jvp within one expression)"
                        | Some fd ->
                            // Stamp the ambient synthesis span with the
                            // ROOT source decl's span (composition chains
                            // inherit it) before building the derivative.
                            Blade.Ast.synthSpan <- (Map.tryFind fname funcSpans |> Option.defaultValue Blade.Ast.synthSpan)
                            let ctx2 = ctxFor fname
                            // A synthesized source is trusted: it binds
                            // reserved names by construction, and the
                            // shadowing hazard the reserved gate guards
                            // against is a user-code phenomenon.
                            let trusted = not (Map.containsKey fname funcDecls)
                            let result =
                                if mode = "grad" then synthesize ctx2 fd
                                elif mode = "vjp" then synthesizeVjp ctx2 fd
                                else synthesizeJvp ctx2 trusted fd
                            result |> Result.map (fun gd ->
                                // BLADE_GRAD_DUMP=1: print the synthesized declaration
                                // (F# structural form) to stderr -- the only view of
                                // what the transform emitted, since no surface
                                // pretty-printer exists.
                                (match System.Environment.GetEnvironmentVariable "BLADE_GRAD_DUMP" with
                                 | null | "" | "0" -> ()
                                 | _ -> eprintfn "[grad dump] %s = %A" synthName gd)
                                available <- Map.add synthName gd available
                                madeOrder.Add synthName
                                madeMap.[synthName] <- (gd, fname))))
                    (Ok ())
            // On failure, LEAVE synthSpan stamped (the `expand` boundary
            // reads it for the diagnostic). Reset on success only.
            match synthResult with
            | Error e -> Error e
            | Ok () ->
                Blade.Ast.synthSpan <- noSpan
                // Splice each synthesized decl after its ROOT source decl,
                // in synthesis order (f, f__grad, f__grad__jvp, ...).
                let rootOf (synthName: string) =
                    let rec go n =
                        match madeMap.TryGetValue n with
                        | true, (_, src) -> if Map.containsKey src funcDecls then src else go src
                        | _ -> n
                    go synthName
                Ok (decls' |> List.collect (fun d ->
                    match d.Value with
                    | DeclFunction fd ->
                        let mine =
                            madeOrder
                            |> Seq.filter (fun sn -> rootOf sn = fd.Name)
                            |> Seq.map (fun sn -> { d with Value = DeclFunction (fst madeMap.[sn]) })
                            |> List.ofSeq
                        // An AD TARGET's OWN body is fused too, so the primal
                        // leg agrees structurally with the tangent leg. Fusion
                        // is the proved Compose-Apply identity, so this cannot
                        // change an answer -- and it is what lets the primal
                        // pipeline shapes the codegen cannot yet emit
                        // (3+ stages, multi-operand, function-body `<$>`/`@>>`)
                        // still be differentiated. A DECLINE here is silent:
                        // the unfused body is legal exactly as the user wrote
                        // it, and the derivative already succeeded.
                        let d =
                            if List.isEmpty mine then d
                            else { d with Value = DeclFunction { fd with Body = fst (fuseFunctionBody (ctxFor fd.Name) fd) } }
                        d :: mine
                    | _ -> [d]))))

/// C7 generalized: the SAME pipeline fusion the AD path runs, applied to
/// EVERY program.
///
/// Why here and not in Lowering: fusion is a statement about SURFACE terms
/// (`>>@`, `@>>`, `<$>` and the kernels behind their names), and by the time
/// an IR pass could see it the pipeline has already been split into the
/// staged buffers this rewrite exists to avoid. Running it as a surface
/// normalization -- in Grad.fs's own phase slot, immediately before
/// `Grad.expand` and therefore before typecheck -- also means AD and the
/// primal see exactly one rewrite, not two implementations of it.
///
/// It is not an optimization pass, it is a repair: without it, three-stage
/// pipelines emit `r__s1[__i0] = ((void)0);`, multi-operand pipelines emit
/// reads of an undeclared `arr0`, and `let p = o1 >>@ o2`, `f <$> c` and
/// `c1 @>> c2` inside a function body all die BL7004 "in expression
/// position". Fusion is the proved Compose-Apply identity
/// (formalism.md 10.3), so none of those repairs can change an answer.
///
/// Declines are SILENT here, unlike in differentiated code: a shape fusion
/// will not touch is one the existing IRComposeApply path still handles.
let fuseProgram (program: Program) : Program =
    let fuseModule (m: ModuleDecl) : ModuleDecl =
        let typeAliases =
            m.Decls |> List.collect (fun d ->
                match d.Value with
                | DeclType (TyDeclAlias (n, [], body)) -> [(n, body)]
                | DeclType (TyDeclMutualGroup (members, _)) -> members
                | _ -> [])
            |> Map.ofList
        // Module bindings -- values AND function declarations -- accumulate in
        // DECLARATION ORDER: a body may only resolve through names bound before
        // it (plus its own, since a named function may self-recurse), which is
        // the language's own visibility rule. `funcDecls` used to be a
        // whole-module map, so a pipeline stage could resolve to a function
        // declared LATER: `(object_for(inc) >>@ object_for(dbl)) <@> A` fused
        // and RAN with both kernels declared below it, where the checker's rule
        // says BL2001. Fusion must not launder a forward reference into a
        // program the checker never sees.
        let mutable env : Map<string, Expr> = Map.empty
        let mutable arrays : Set<string> = Set.empty
        let mutable funcDecls : Map<string, FunctionDecl> = Map.empty
        // ONE counter cell for the whole module, so the per-decl contexts below
        // keep minting distinct names (see Ctx.Fresh).
        let freshCell = ref 0
        let ctxNow () =
            { Decls = funcDecls; TypeAliases = typeAliases; ModuleVals = Set.empty
              ModuleLets = Map.empty; Fresh = freshCell
              NormMemo = System.Collections.Generic.Dictionary()
              PackMemo = System.Collections.Generic.Dictionary() }
        let noteBinding (pat: Pattern) (v: Expr) =
            match pat.Kind with
            | PatternKind.PatVar nm ->
                env <- (if bindsPipelineValue v then Map.add nm v env else Map.remove nm env)
                arrays <- (if isArrayish arrays v v then Set.add nm arrays else Set.remove nm arrays)
            // A destructuring module binding rebinds each of its names. Nothing
            // here can say what a component holds, so they are dropped from
            // both maps rather than left pointing at an earlier binding of the
            // same name (the block fold's non-PatVar arm does the same).
            | _ ->
                for nm in patternBoundNames pat do
                    env <- Map.remove nm env
                    arrays <- Set.remove nm arrays
        let decls =
            m.Decls |> List.map (fun d ->
                match d.Value with
                | DeclFunction fd ->
                    // Visible to its own body: everything declared above, plus
                    // itself (self-recursion is legal; mutual recursion is not).
                    funcDecls <- Map.add fd.Name fd funcDecls
                    if not (containsPipelineOp fd.Body) then d else
                    let ctx = ctxNow ()
                    let ps = fd.Params |> List.map _.Name |> Set.ofList
                    let paramArrays =
                        fd.Params
                        |> List.filter (fun p ->
                            match p.Type with
                            | Some t -> (match resolveArrayTy ctx t with TyArray _ -> true | _ -> false)
                            | None -> false)
                        |> List.map _.Name
                        |> Set.ofList
                    let body, _ =
                        fusePipelinesEnvIn ctx
                            (env |> Map.filter (fun n _ -> not (Set.contains n ps)))
                            (Set.union (Set.difference arrays ps) paramArrays)
                            (fd.Params |> List.map _.Name)
                            fd.Body
                    { d with Value = DeclFunction { fd with Body = body } }
                // `noteBinding` runs either way: the env has to stay accurate
                // even for the bindings the pre-scan skipped rewriting.
                | DeclLet b ->
                    if not (containsPipelineOp b.Value) then (noteBinding b.Pattern b.Value; d) else
                    let v, _ = fusePipelinesEnv (ctxNow ()) env arrays b.Value
                    noteBinding b.Pattern v
                    { d with Value = DeclLet { b with Value = v } }
                | DeclStatic b ->
                    if not (containsPipelineOp b.Value) then (noteBinding b.Pattern b.Value; d) else
                    let v, _ = fusePipelinesEnv (ctxNow ()) env arrays b.Value
                    noteBinding b.Pattern v
                    { d with Value = DeclStatic { b with Value = v } }
                | _ -> d)
        { m with Decls = decls }
    { program with Modules = program.Modules |> List.map fuseModule }

/// Entry point: expand grad() across a program. Errors are compile errors.
let private expandStr (program: Program) : Result<Program, string> =
    program.Modules
    |> List.fold (fun acc m ->
        acc |> Result.bind (fun ms ->
            expandModule m.Decls |> Result.map (fun ds -> ms @ [{ m with Decls = ds }])))
        (Ok [])
    |> Result.map (fun ms -> { program with Modules = ms })

/// Boundary: string-errored internals -> coded diagnostics. The span is the
/// ambient synthSpan -- stamped per-decl by expandStr, so a mid-elaboration
/// failure points at the offending declaration.
let expand (program: Program) : Result<Program, Blade.Diagnostics.Diagnostic list> =
    Blade.Ast.synthSpan <- Blade.Ast.noSpan
    let result =
        expandStr program
        |> Result.mapError (fun msg ->
            // The pack unroller's marker outranks the mode prefix: a kernel
            // that cannot be unrolled at this arity is the same refusal in
            // both modes, so it carries its own code. Everything else is
            // coded by MODE -- jvp-phase messages carry the "jvp(" prefix
            // (errMode) or the "jvp:" rewrite prefix; the rest is grad's.
            let isPack = msg.StartsWith packUnrollMarker
            let msg = if isPack then msg.Substring packUnrollMarker.Length else msg
            let code =
                if isPack then "BL5502"
                elif msg.StartsWith "jvp" then "BL5501"
                else "BL5500"   // grad's and vjp's (the seeded reverse mode shares grad's subset and code)
            [ Blade.Diagnostics.mkError code (Blade.Diagnostics.Codes.phaseOfCode code) Blade.Ast.synthSpan msg ])
    // Reset AFTER the diagnostic is built (the span is the failing decl's),
    // so no stamp leaks into later passes.
    Blade.Ast.synthSpan <- Blade.Ast.noSpan
    result
